### ISSUE TITLE
add dask support for multiprocessing

### ISSUE THREAD

**Issue by bparbhu** [uber/orbit#240]
Hey all, 

I love the work you guys are doing with multivariate time series analysis using stan and pyro! Is it possible to have dask support in addition to multiprocessing in stan_estimators.py? I also wouldn't mind helping out to make this happen. 

Thanks again for this,

-Brian

**Comment by steveyang90** [comment]
Hey Brian -- thanks for the interest! To clarify a bit, we currently only use `multiprocessing` to determine system cpu count and the parallelization is happening within PyStan. For prediction we use PyTorch so the math is vectorized.

What did you have in mind with dask, definitely open to hearing more!

**Comment by bparbhu** [comment]
Ahhh I see, my mistake. Well, there is a use case I think if you're going to try and do some form of cross validation. I would be interested in doing that if that's a possibility.

**Comment by bparbhu** [comment]
Maybe also using dask to calculate performance metrics as well.

**Comment by steveyang90** [comment]
I think for now we'll avoid extra dependencies, but it would be interesting to see if this works better than using torch when we think about implementing multivariate models down the line

**Comment by bparbhu** [comment]
Cool
