### ISSUE TITLE
LGT doesn't handle negative numbers

### ISSUE THREAD

**Issue by j2kun** [uber/orbit#258]
**Describe the bug**
LGTMAP and LGTFull fail with the following error when any response variable is negative

```
  File "stanfit4anon_model_e3c37ca0adcdb861bca79a20c503522f_2651646156859608841.pyx", line 479, in stanfit4anon_model_e3c37ca0adcdb861bca79a20c503522f_2651646156859608841.StanFit4Model.__cinit__
ValueError: Exception: anon_model_e3c37ca0adcdb861bca79a20c503522f_namespace::anon_model_e3c37ca0adcdb861bca79a20c503522f: RESPONSE[2] is -1.65, but must be greater than or equal to 0  (in 'unknown file name' at line 25)
```

**To Reproduce**

Save the following file as "snp.tsv": https://gist.github.com/j2kun/7c984ec1c47e13bd54466c2b63348dae

Then run

```
from orbit.models import lgt
import numpy as np
import pandas as pd

df = pd.read_csv("snp.tsv", sep='\t', parse_dates=['Month'])
df = df.sort_values(by='Month')
test_size = 36
train_df = df[:-test_size]
test_df = df[-test_size:]

model = lgt.LGTMAP(   # or LGTFull
    response_col='Percent change',
    date_col='Month',
    seasonality=12,
)
model.fit(df=train_df)
```

**Expected behavior**
Model trains.

**Environment (please complete the following information):**
 - OS: macOS
 - Python Version: 3.8
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`):

numpy==1.19.2
pystan==2.19.1.1
pandas==1.1.3

**Comment by j2kun** [comment]
Note, the data is intended to be negative, as it is a percent change.

**Comment by edwinnglabs** [comment]
Hi @j2kun `LGT` by designed, it is used for strictly positive response (due to some power term of the global trend).  I would suggest you to use `DLTMAP` and `DLTFULL` intead

**Comment by j2kun** [comment]
It may be worthwhile to note this in the documentation, since LGT is presented there and I was trying to reproduce it on a random dataset I had.

**Comment by edwinnglabs** [comment]
@j2kun It is a very good suggestion.  We will put it in the note.
