### ISSUE TITLE
How does Orbit compare to Profet?

### ISSUE THREAD

**Issue by jboarman** [uber/orbit#268]
What is the motivation of Orbit as it compares to Profet?

Are there any performance benchmarks available that compare the two?

**Comment by steveyang90** [comment]
We did some benchmarks in the draft of our [paper](https://arxiv.org/pdf/2004.08492.pdf)

In general, we saw improvements over Prophet on datasets we benchmarked against, and especially so for our specific tasks which was for media mix model use-case. With that being said, forecasting can be very task dependent, and it would be great to expand this analysis to more datasets.

**Comment by jboarman** [comment]
Thanks @steveyang90 for that reference.  I have pasted the most interesting facts on the performance comparison below to save some time for others interested in the answer:

> We compared our proposed models, LGT and DLT, to other popular time series models such as SARIMA (Seabold &Perktold, 2010) and Facebook Prophet (Taylor & Letham,2018).
> ...
>It shows that our models consistently deliver better accuracy than other candidate time series models in terms of SMAPE. Orbit is also computationally efficient.  For example, the average compute time per series with full MCMC sampling and prediction from a subset of M4 weekly data is about *2.5 minutes* and *16 ms*.  The run time for the same series in Prophet is about *10 minutes* for sampling and *2.4 s* for prediction.  **That’s a 4x speed up in training, and orders of magnitude difference in prediction.**

**Comment by steveyang90** [comment]
@jboarman also if you have other datasets in mind for further benchmarks, we'd highly encourage and appreciate any additional feedback or analysis!
