### ISSUE TITLE
No graph output from plot_predicted_data

### ISSUE THREAD

**Issue by swotai** [uber/orbit#271]
**Describe the bug**
There's no graph output from plot_predicted_data

**To Reproduce**
I tried following the starter code from the LGT model documentation, swapping in my own dataset and col labels. See screenshot

**Expected behavior**
A graph to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/9345420/98393848-bb5d0a80-200e-11eb-810b-e2ccc178e58b.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS on WSL
 - Python Version: 3.8.2
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): `pandas==1.1.4`, `scikit-learn==0.23.2`, `cython==0.29.21`, `matplotlib==3.2.1`

**Comment by ramyahrgowda** [comment]
I too faced this issue. As a temporary fix, I use "%matplotlib inline" before plotting and it works.
# plot predictions
%matplotlib inline
plot_predicted_data(
    training_actual_df=train_df, predicted_df=predicted_df,
    date_col=lgt.date_col, actual_col=lgt.response_col,
    pred_col='prediction', test_actual_df=test_df
)

**Comment by steveyang90** [comment]
@swotai to unblock you for now, could you try `%matplotlib inline` in your notebook as @ramyahrgowda suggested. We'll investigate further on our end to see if we can globally force the plot to show inline.

@ramyahrgowda could you share what environment you're using as well and also if you're using Jupyter Notebook or Jupyter Lab? I'm wondering if there is any commonalities for which matplotlib doesn't display automatically.

**Comment by swotai** [comment]
Or simply add the `%matplotlib inline` in the tutorial will probably do.
Thanks!!
