### ISSUE TITLE
Remove enum34 dependency

### ISSUE THREAD

**Issue by CrossNox** [uber/orbit#299]
**Describe the bug**
The enum34 dependency is not required. The classifiers on `setup.py` specify versions `3.6` and `3.7` of python. The package `enum34` is a backport of `python3.4` enums for previous versions of the language.

**Suggested fix**
Remove the dependency from `requirements.txt`. Doing so does not prevent all tests from passing.

**Additional context**
I might be missing why it was included in the first place, but on a project using `python3.7+`, it breaks installation of the package because of conflicts `enum34` introduces. I'm willing to send a PR, it's a really small fix.

**Comment by steveyang90** [comment]
Thanks for pointing this out @CrossNox! I don't seem to be able to replicate breaking installation on `python3.7`, but I do believe you're right that we don't need this requirement. This is just requirements left over from previously supporting `python2.7`.

Please feel free to submit a PR! We'd be grateful for the contribution and happy to merge if all tests still pass

**Comment by CrossNox** [comment]
Thanks for replying @steveyang90, I just opened #301 to address this. I think I didn't explain myself properly before, installing on a a clean python3.7 environment does not break but installing alongside some other dependencies on a project I'm involved in does break because of the `enum34` installation.  I haven't been able to track where the issue is exactly, but I still think this could be an improvement :smile: 

Sorry for not having anything more significant to contribute, and thanks for this great library!

**Comment by steveyang90** [comment]
ahhh I see what you mean now! Thanks for the PR!
