### ISSUE TITLE
populate doc strings from the parent classes

### ISSUE THREAD

**Issue by wangzhishi** [uber/orbit#333]
inherit doc strings from the parent classes so that they can be displayed when using the child classes

**Comment by ppstacy** [comment]
Ooops, sorry I didn't see you assign this to Steve. I just updated in commit https://github.com/uber/orbit/commit/7a752a69d391b0588767eca48403c630612513c2 and https://github.com/uber/orbit/commit/68cff5eff2c2fd506c8648381e68d47640d66631. It looks good [here](file:///Users/jing.pan/Projects/orbit-readthedocs/tutorials.html). Please take a look and let me know anything that need to chang. Thanks!
