### ISSUE TITLE
A clearer representation of backtest, holdout prediction

### ISSUE THREAD

**Issue by edwinnglabs** [uber/orbit#356]
**Is your feature request related to a problem? Please describe.**
A clearer representation of backtest, holdout prediction.

**Describe the solution you'd like**
1. Allow option of line/points plot of predictions
2. some segment / dotted line to separate train and holdout period
3. animation on backtest to represent multiple splits

**Comment by vincewu51** [comment]
For point 3, do we want to have an animation/plot whenever the user calls backeteser?

**Comment by edwinnglabs** [comment]
> For point 3, do we want to have an animation/plot whenever the user calls backeteser?

Maybe, we can just have a utility do accept the similar format of output from backtester instead of an auto-trigger.
