### ISSUE TITLE
Working around  PyStan compilation in Python 3.9.0

### ISSUE THREAD

**Issue by mrp011** [uber/orbit#376]
I am newly installing orbit 1.0.12 on python 3.9.0.

After a basic `pip install orbit-ml` I tried to run the code from the quickstart and received the familiar message when fitting the model:

`INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_19a09b474d1901f191444eaf8a6b8ce2 NOW`

However, the code would never complete and looking at the notebook logs I had the following error: 

`ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_3165257500684989992`

I googled the error, and found the following articles:

[from pystan2 issues](https://github.com/stan-dev/pystan2/issues/748)
[from mc-stan discourse](https://discourse.mc-stan.org/t/new-to-pystan-always-get-this-error-when-attempting-to-sample-modulenotfounderror-no-module-named-stanfit4anon-model/19288)

which led me to the following solution. Prior to building a model with pystan (or orbit), I should run:

```
import multiprocessing
multiprocessing.set_start_method("fork")
```

I do need to run this every time I want to run a notebook with models. Not just on the initial compilation. There may be a way to mitigate this issue within the orbit package.

**Comment by edwinnglabs** [comment]
It seems i can replicate the problem with message as such 
```
WARNING:pystan:No module named 'stanfit4anon_model_54eae5ecf2d426f33baa7b746b329122_417398889354327494'
WARNING:pystan:Something went wrong while unpickling the StanModel. Consider recompiling.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-cc27eba592a7> in <module>
----> 1 mod.fit(data)

~/work/orbit-super/orbit/orbit/models/template.py in fit(self, df)
    316 
    317     def fit(self, df):
--> 318         super().fit(df)
    319         self._set_map_posterior()
    320 

~/work/orbit-super/orbit/orbit/models/template.py in fit(self, df)
    220         # note that estimator will search for the .stan, .pyro model file based on the
    221         # estimator type and model_name provided
--> 222         model_extract = estimator.fit(
    223             model_name=model_name,
    224             model_param_names=model_param_names,

~/work/orbit-super/orbit/orbit/estimators/stan_estimator.py in fit(self, model_name, model_param_names, data_input, fitter, init_values)
    285         # in case optimizing fails with given algorithm fallback to `Newton`
    286         try:
--> 287             stan_extract = compiled_stan_file.optimizing(
    288                 data=data_input,
    289                 init=init_values,

~/work/venv/py39_ts/lib/python3.9/site-packages/pystan/model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    540             data = {}
    541         seed = pystan.misc._check_seed(seed)
--> 542         fit = self.fit_class(data, seed)
    543 
    544         m_pars = fit._get_param_names()

AttributeError: 'StanModel' object has no attribute 'fit_class'
```

**Comment by Okroshiashvili** [comment]
Hey @mrp011 . Is this related to the #468 ?
