### ISSUE TITLE
gris search error 

### ISSUE THREAD

**Issue by orydatadudes** [uber/orbit#436]
**Describe the bug**
getting "TypeError: __init__() got an unexpected keyword argument 'min_nu'" when running the [tuning notebook example](https://github.com/uber/orbit/blob/dev/examples/hyper_parameters_tuning.ipynb)

**Comment by wangzhishi** [comment]
> **Describe the bug**
> getting "TypeError: **init**() got an unexpected keyword argument 'min_nu'" when running the [tuning notebook example](https://github.com/uber/orbit/blob/dev/examples/hyper_parameters_tuning.ipynb)

@orydatadudes thanks for bringing up this issue, which was due to some changes in the codebase recently. It is fixed in the [PR](https://github.com/uber/orbit/pull/438).
