### ISSUE TITLE
Allow Bayesian Evidence, Log Posterior, ELBO Loss Extraction

### ISSUE THREAD

**Issue by edwinnglabs** [uber/orbit#444]
Right now, we don't expose Bayesian Evidence, Log Posterior, ELBO Loss Extraction in a systematic way.  To allow us to do so, it may enable us to better inform model convergence and other diagnostic such as WAIC for model selection.

We can start with a basic `get_traning_metrics()` and return a dictionary of meta data.

**Comment by ArkaprabhaChakraborty** [comment]
Hi Edwin! Can you guide me on how to work on this issue if nobody is working on it?

**Comment by edwinnglabs** [comment]
> Hi Edwin! Can you guide me on how to work on this issue if nobody is working on it?

This is already done.  See [tutorial](https://orbit-ml.readthedocs.io/en/latest/tutorials/pyro_basic.html) for details.  We are planning to extract other bayesian information such as [DIC](https://en.wikipedia.org/wiki/Deviance_information_criterion).
