### ISSUE TITLE
__init__() got an unexpected keyword argument 'min_nu' in Grid Search

### ISSUE THREAD

**Issue by Okroshiashvili** [uber/orbit#457]
**Describe the bug**
Got strange error while doing grid search.

**To Reproduce**
```
dlt_params = {
             "seasonality_sm_input": [0.3, 0.5, 0.8],
             "level_sm_input": [0.01, 0.1, 0.3, 0.5, 0.8]}


dlt = DLTFull(response_col="target",
             date_col="date", seasonality=7)

grid_search_orbit(dlt_params,model=dlt,
                  df=df_brand, min_train_len=120,
                  incremental_len=30, forecast_len=14,
                  metrics=None, criteria=None, verbose=True)
```

**Expected behavior**
Expected to have a grid search but I got error enstead.

**Screenshots**
![image](https://user-images.githubusercontent.com/20360326/122861580-b2684180-d330-11eb-85ae-e9fb658673d7.png)
![image](https://user-images.githubusercontent.com/20360326/122861618-c57b1180-d330-11eb-9cd3-2945b33f1f72.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version: 3.7

**Extra Notes**

I use orbit version `1.0.13` and your tutorials have the same bug for this version of orbit

**Comment by wangzhishi** [comment]
@Okroshiashvili Thanks for bringing this up. This bug has been fixed in the `dev` branch (but not in the release `v1.0.13`). So, you need to install the `dev` branch if you want to fully leverage the grid search feature now. We will include this fix in next release.

**Comment by Okroshiashvili** [comment]
@wangzhishi thanks for quick replay. I've installed dev branch and grid search works as expected. Closing the issue
