### ISSUE TITLE
DLT and LGT models cannot handle negative response values

### ISSUE THREAD

**Issue by Okroshiashvili** [uber/orbit#458]
**Describe the bug**
In the documentation you mention that LGT cannot handle negative values of response variable. However, I encountered the same error using DLT model.

Does DLT handle negative values in response variable?

**Screenshots**
DLT model

![image](https://user-images.githubusercontent.com/20360326/122928894-58409e00-d37b-11eb-9e52-2d62ead4d0d8.png)

I have same error when using LGT model

**Environment (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Python Version: 3.7

**Additional context**

I use Orbit version `1.0.14dev`

**Comment by wangzhishi** [comment]
@Okroshiashvili just to confirm before we proceed to fix this bug, are the values in your response variable all negative?

**Comment by Okroshiashvili** [comment]
Hi @wangzhishi .Yes, all values in response are negative. To reproduce the behavior, sample random variables in (0, 1] interval and then take natural logarithm.

**Comment by wangzhishi** [comment]
we merged a PR to dev branch to solve this bug. please try it out. thanks!
