### ISSUE TITLE
Multivariate Predict Univariate

### ISSUE THREAD

**Issue by veioxve3r1d23seb2g6b** [uber/orbit#467]
Is it possible to forecast with multiple regressors?

num_periods = 365
freq = 1
last_dt = (df["time"].dt.to_pydatetime())[-1]
print(last_dt)
dts = [last_dt + timedelta(days=x * freq) for x in range(1, num_periods + 1)]
future_df = pd.DataFrame(dts, columns=["time"])

dlt = DLTMAP(
    response_col='y', 
    date_col='time',
    regressor_col=list(filter(lambda i: i !="time" and i !="y", df.columns)),
    seasonality=52,
    seed=9,
)

dlt.fit(df=df)

predicted_df = dlt.predict(df=future_df, decompose=True)

plot_predicted_data(
    training_actual_df=df, 
    predicted_df=predicted_df,
    date_col=dlt.date_col, 
    actual_col=dlt.response_col,
    title="DLT Model with Linear Trend"
)

I'm getting none of the index are in the columns.

KeyError: "None of [Index(['........'],\n      dtype='object', length=309)] are in the [columns]"

**Comment by wangzhishi** [comment]
yes, orbit does support multiple regressors. you can take a look at this [example notebook](https://orbit-ml.readthedocs.io/en/stable/tutorials/dlt.html), section `Regression`. You may want to double check if the `regressor_col` you supplied are in your `df`.
