### ISSUE TITLE
Error when running example notebooks

### ISSUE THREAD

**Issue by Okroshiashvili** [uber/orbit#468]
**Describe the bug**
After pulling dev branch and run the example notebook got this error. Below are screenshots

**To Reproduce**
Run example notebook `dlt.ipynb`

**Screenshots**
![image](https://user-images.githubusercontent.com/20360326/126060052-180dc6c3-51e1-41f9-8d55-a83d61013e76.png)

![image](https://user-images.githubusercontent.com/20360326/126060057-78e94a97-790e-486b-99b4-65a5dd0354a0.png)

![image](https://user-images.githubusercontent.com/20360326/126060072-45c7292d-ec05-4c91-9cfb-daa095eb1637.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.7 and 3.8
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): I used `requirements.txt`

**Comment by Okroshiashvili** [comment]
Is there any news regarding this issue? I'm getting the same error for Orbit version `1.0.13` and `1.0.12`

**Comment by edwinnglabs** [comment]
It doesn't seem to me the error is associated with screen you print.  I wonder if you are having similar issue as #376 which I have just fixed recently.

**Comment by thxi** [comment]
I think I found the solution to this issue.

Environment:
    orbit-ml: 1.0.17
    OS: Ubuntu
    Python Version: 3.8.10
    Versions of Major Dependencies (pandas, scikit-learn, cython): [requirements.txt](https://pastebin.com/S5gyErzN), I have just used `pip install orbit-ml` in a fresh virtual environment.


The problem is stan is unable to compile the model when using the jupyter notebook. However, if I run the same code in `.py` script, the model compiles successfully. After that, I go to jupyter notebook to run the code and the `.fit` method runs successfully (since stan did not have to compile the model).

The sample code that I used:
```python
import multiprocessing
import numpy as np
import orbit
import datetime
from orbit.utils.dataset import load_iclaims
from orbit.models.dlt import ETSFull, DLTMAP, DLTFull
from orbit.models.lgt import LGTMAP, LGTFull
from orbit.diagnostics.plot import plot_predicted_data


print("CONTEXT", multiprocessing.get_context())
multiprocessing.set_start_method("fork", force=True)  # fork by default on my system
print(f"{orbit.__version__=}")

df = load_iclaims()
date_col = 'week'
response_col = 'claims'
print(df.head())

test_size = 52
train_df = df[:-test_size]
test_df = df[-test_size:]

dlt = LGTMAP(
    response_col=response_col,
    date_col=date_col,
    regressor_col=['trend.unemploy', 'trend.filling', 'trend.job', 'sp500', 'vix'],
    regressor_sign=["+", '+', '=', '-', '+'],
    seasonality=52,
    seed=8888,
)

print("START FIT", datetime.datetime.now())
print("CONTEXT", multiprocessing.get_context())  # should be fork

dlt.fit(df=train_df)  # jupyter will hang forever here if the model have not been compiled

print("END FIT", datetime.datetime.now())

predicted_df = dlt.predict(df=test_df)

_ = plot_predicted_data(train_df, predicted_df, date_col, response_col, title='Prediction with ETS')
```
