### ISSUE TITLE
Create workflow for checking MacOS and Windows

### ISSUE THREAD

**Issue by edwinnglabs** [uber/orbit#489]
**Is your feature request related to a problem? Please describe.**
Right now we don't have specific tests on MacOS and Windows.  We may need them for full coverage on common OS

**Describe the solution you'd like**
A workflow that is triggered just on pre-release / merge on [dev / master ]etc. could be much more infrequent than standard pytest coverage.

**Comment by edwinnglabs** [comment]
@szmark001

**Comment by szmark001** [comment]
https://github.com/uber/orbit/pull/561
