### ISSUE TITLE
RuntimeError: Initialization failed for nan regressors

### ISSUE THREAD

**Issue by iharshulhan** [uber/orbit#560]
**Describe the bug**
When the DLTMAP model receives regressors with nan values it crashes with the ``RuntimeError: Initialization failed.`` Further in the logs one can find a following error: 
``Exception: student_t_lpdf: Location parameter is nan, but must be finite!  (in 'unknown file name' at line 282)``

**To Reproduce**
Fit the DLT model with additional regressors containing nans.

**Expected behavior**
After passing the nan values,  an error message should be returned specifying that nans are not accepted by the model.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.7
 - Versions of Major Dependencies: pystan==2.19.1.1, orbit-ml==1.0.17

**Comment by edwinnglabs** [comment]
@iharshulhan are you passing some invalid values of your regressor (specified by the `regressor_col`)? right now we don't support missing values for regressors.

**Comment by iharshulhan** [comment]
@edwinnglabs Yes, but as I specified in the issue, the problem is not a support of those values, but appropriate exception handling. Currently, there is no hint from where the error is coming from, because you only see a ``RuntimeError: Initialization failed``. This message is uninformative and makes it hard to debug.
