### ISSUE TITLE
grid_search_orbit missing in pip install 

### ISSUE THREAD

**Issue by ggerogiokas** [uber/orbit#580]
Hi,

Thanks for the great package! 

Just noticed that **params_tuning** module is missing at least in my pip install on a **windows** machine.

![image](https://user-images.githubusercontent.com/12640374/132841582-4bfde610-ac55-4af7-a603-a01358ea0d00.png)

Thanks,
George

**Comment by wangzhishi** [comment]
Hi @ggerogiokas, what is your installed orbit version? I guess it is v1.0.17? If this is the case, I recommend you to look at the examples in the `master` branch.

If you want to run the example notebooks in the latest `dev` branch, you need to install the dev branch first. 

We are actively working on a new version v1.1.0, which has a gap with the released stable version.

**Comment by ggerogiokas** [comment]
Hi @wangzhishi,

Thanks I tried the dev and it's working fine :D!
