### ISSUE TITLE
plot_predicted_components fails to plot with trend component only

### ISSUE THREAD

**Issue by FreeRealEstate221** [uber/orbit#584]
**Describe the bug**
plot_predicted_components would raise an error when the argument plot_components = ['trend']

**Screenshots**
![Screen Shot 2021-09-14 at 2 39 58 PM](https://user-images.githubusercontent.com/71520155/133315142-947d110f-e41c-48db-b238-831cd40adabd.png)

**Comment by edwinnglabs** [comment]
Could you also provide the model you are fitting and the configs?

**Comment by FreeRealEstate221** [comment]
sure. I'm using KTR-Lite with the following config. (I encountered this issue in the example notebook: https://github.com/uber/orbit/blob/dev/examples/ktrlite.ipynb)
![Screen Shot 2021-09-15 at 5 20 19 PM](https://user-images.githubusercontent.com/71520155/133511116-6b828f50-f010-4aff-8a7c-4fe3761b105d.png)
