### ISSUE TITLE
More user friendly reminder of data gap

### ISSUE THREAD

**Issue by iharshulhan** [uber/orbit#586]
**Describe the bug**
Following error occures while fitting some KTR models:
 **ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)**

Stacktrace:
```
    dlt_reg.fit(df=df, point_method='mean')
File "/opt/conda/envs/lib/python3.7/site-packages/orbit/forecaster/svi.py", line 25, in fit
    super().fit(df)
File "/opt/conda/envs/lib/python3.7/site-packages/orbit/forecaster/forecaster.py", line 128, in fit
    self._model.set_dynamic_attributes(df=df, training_meta=self.get_training_meta())
File "/opt/conda/envs/lib/python3.7/site-packages/orbit/template/ktr.py", line 798, in set_dynamic_attributes
    self._set_levs_and_seas(df, training_meta)
File "/opt/conda/envs/lib/python3.7/site-packages/orbit/template/ktr.py", line 768, in _set_levs_and_seas
    self._seasonality_fs_order)
File "/opt/conda/envs/lib/python3.7/site-packages/orbit/template/ktr.py", line 682, in _generate_seas
    seas_coef = np.squeeze(np.matmul(coef_knot, coef_kernel.transpose(1, 0)), axis=0).transpose(1, 0)
```
**Environment (please complete the following information):**
 - OS: Ubuntu
 - Python Version: 3.7
 - orbit-ml==1.1.0dev

**Comment by wangzhishi** [comment]
hi @iharshulhan, thanks for raising this bug. do you have a minimal example with data to reproduce this bug? If so, I can look into it. otherwise, it is hard for us to identity what is the problem.

**Comment by iharshulhan** [comment]
Yes, the problem occurs when dates between samples are not even. I've attached a sample to reproduce the error. 
[sample.zip](https://github.com/uber/orbit/files/7195481/sample.zip)

```
from orbit.models import KTR

model = KTR(seasonality=[12])
model.fit(df)
```

**Comment by wangzhishi** [comment]
yea, that is the root cause of the error. we expect the dates to be on the same frequency.

the date gaps in your data vary a lot. sometimes daily, sometimes weekly, or even several months gap. In this case, how to claim the seasonality and expect the model to capture it?

**Comment by iharshulhan** [comment]
First of all, If there is such expectation, it would be great to state it somewhere and introduce proper warnings/errors to handle the data. Right now matmul error is not very informative. 

Secondly, this expectation would significantly limit the usage of the tool with real world data. The date gaps is a problem of missing data points, we may fit the seasonality term on available points and interpolate in between. In the specific example the problem appears only with last 15 points, where there is a gap of several months.

**Comment by edwinnglabs** [comment]
@iharshulhan  Try to clarify this, KTR does come up with a nice property to skip missing values as long as user code that observation up as a null entry. So my guess is we can have a general module to detect all the gaps with some assumption of the observations frequency and fill a null values there. Then from there, KTR should be able to pick up the work. Hope that makes sense.

**Comment by edwinnglabs** [comment]
Redefine the scope of this as making a more user friendly message when user accidentally input a dataset with gaps (inconsistent gaps).
