### ISSUE TITLE
“Bayesian Time Varying Coefficient Model with Applications to Marketing Mix Modeling”

### ISSUE THREAD

**Issue by TimKreienkamp** [uber/orbit#590]
Hi,

in their mind-blowing [paper](https://arxiv.org/pdf/2106.03322.pdf ) named above, the authors state they implemented their proposed method as a feature branch in orbit. Could you point me to that branch, in case it's public?

Thanks a lot!

Tim

**Comment by wangzhishi** [comment]
The BTVC model is termed as KTR model in the package. Here is one tutorial: https://orbit-ml.readthedocs.io/en/latest/tutorials/ktr1.html
