### ISSUE TITLE
DLT fails to fit some time series

### ISSUE THREAD

**Issue by imanebosch** [uber/orbit#595]
**Bug description**

We fitted DLT using synthetic seasonal time series, but for some reason orbit does not perform as expcted.
We get a wierd forecast for a series that is fairly regular. 

Observation: We noticed that after normalizing or log transforming the target variable these issues are less likely to happend. Does it have anything to do with the numerical stability of the optimizer?

Synthetic time series:
  
![image](https://user-images.githubusercontent.com/22483212/136359010-9188ad3f-0907-4e50-8c8a-b16a369d42c0.png)

**To Reproduce**

Fit a DLT model using [orbit_data.csv](https://github.com/uber/orbit/files/7301067/orbit_data.csv) such that:

```python
train_set = data.iloc[0:-100,:]
test_set = data.iloc[-100:, ]

dlt = DLTMAP(
    response_col='y',
    date_col='date',
    seasonality=52,
    seed=8574,
    regressor_col=['x'],
    regression_penalty='lasso',
)

_ = dlt.fit(df=train_set)
predicted_df = dlt.predict(df=test_set, decompose=True)

_ = plot_predicted_data(
        train_set, predicted_df, 'date', 'y', 
        title="Forecasting", test_actual_df=test_set, figsize=(16,8), 
        is_visible=True
)
```

**Expected behavior**
We expect DLT to capture the time seris pattern, but we get a wierd prediction (see image)

![image](https://user-images.githubusercontent.com/22483212/136357723-b300f2bb-cbbc-438d-ae05-d2368e0a36ba.png)

**Environment:**
 - OS: Windows
 - Python Version: 3.7.11
 - Orbit: 1.0.17

**Comment by edwinnglabs** [comment]
@imanebosch I think the problem you mentioned is mainly due to the constant prior on seasonality.  I guess this should be improved now after we implemented a data-driven seasonality prior.  This feature currently is only included in `dev` branch. Feel free to try it or you can wait a bit for the next version.
