### ISSUE TITLE
Installing orbit with pip on Windows 10

### ISSUE THREAD

**Issue by dishkakrauch** [uber/orbit#603]
**Describe the bug**
Orbit can be installed with pip but it cannot be fitted with pystan backend in case of not supported MSVC compiler.

**To Reproduce**
1. Install Visual Studio 2015/2017/2019 with default C++ compilers including MSVC.
2. Install pystan with conda: **conda install pystan**
2. Install orbit with pip: **pip install orbit-ml**

**Expected behavior**
This code should go without any error:

```
import matplotlib.pyplot as plt

import orbit
from orbit.models.dlt import DLTMAP, DLTFull
from orbit.diagnostics.plot import plot_predicted_data, plot_predicted_components
from orbit.utils.dataset import load_iclaims
from orbit.utils.plot import get_orbit_style

# load log-transformed data
df = load_iclaims()
train_df = df[df['week'] < '2017-01-01']
test_df = df[df['week'] >= '2017-01-01']

response_col = 'claims'
date_col = 'week'
regressor_col = ['trend.unemploy', 'trend.filling', 'trend.job']

dlt = DLTFull(
    response_col=response_col,
    regressor_col=regressor_col,
    date_col=date_col,
    seasonality=52,
    prediction_percentiles=[5, 95],
)

dlt.fit(train_df)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/34490641/137202263-6067ca97-7426-4296-a0f9-4f60ecc3e8f8.png)
![image](https://user-images.githubusercontent.com/34490641/137202284-b5fa3ec2-b8d7-4090-ba25-a46b8a5555fd.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.5
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==1.1.3`, `scikit-learn==0.22.1`, `cython==0.29.21`]

**Additional context**
Prophet works well with this setup.

**Comment by wangzhishi** [comment]
hi @dishkakrauch , this seems to be an issue related to installation pystan 2 on windows. I recommend to follow their [guidance](https://pystan2.readthedocs.io/en/latest/windows.html) to install pystan on windows. After successfully installing pystan, then install orbit and try it out.

Pystan is a requirement for orbit, and it is tricky to use pystan on windows OS. The issue you raised is one problem one level lower before orbit.
