### ISSUE TITLE
Backtest Plot Tutorial

### ISSUE THREAD

**Issue by edwinnglabs** [uber/orbit#621]
@wangzhishi is the plotting of the linear slope expected [here](https://orbit-ml.readthedocs.io/en/latest/tutorials/backtest.html)?

![Screen Shot 2021-11-15 at 3 46 57 PM](https://user-images.githubusercontent.com/43593379/141870415-e1a1368d-789b-41e5-9ca9-b5aa9478622a.png)

**Comment by wangzhishi** [comment]
i reran the tutorial and didn't see such the straight lines.

**Comment by wangzhishi** [comment]
will refresh the tutorial and close the issue.
