### ISSUE TITLE
3 Issues

### ISSUE THREAD

**Issue by LastAncientOne** [uber/orbit#625]
Hi. 

I am using Window 10 and python 3.6.

I got 3 issues.

C:\Users\X\Anaconda3\lib\site-packages\distributed\config.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config.update(yaml.load(text) or {})

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_b0a449c7523386cce384e92a998e71c8 NOW.
WARNING:pystan:MSVC compiler is not supported

CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Please help.

Thank you

**Comment by wangzhishi** [comment]
hi @LastAncientOne , it is tricky to use pystan 2 on windows. According to their [doc](https://pystan2.readthedocs.io/en/latest/windows.html), MSVC is not supported. But, by looking at your error log, you are using the MSCV compiler?

I recommend to follow their instruction to install pystan on windows, and do a testing before you turn to orbit. This is an problem for pystan installation

**Comment by wangzhishi** [comment]
Please refer to the threads below, where some solutions are suggested:

https://github.com/uber/orbit/issues/520#issuecomment-1077937181
https://github.com/uber/orbit/issues/699#issuecomment-1037651616
