### ISSUE TITLE
local variable 'pool' referred before assign

### ISSUE THREAD

**Issue by muthumula19** [uber/orbit#657]
When i am using LGT & DLT model with MCMC estimator i got error like local variable 'pool' referred before assign`dlt = DLT(response_col='Sales',date_col='Date',estimator=estimater,seasonality=seasonality,seed=8888)`

**Comment by muthumula19** [comment]
Windows 10 and python 3.7.11

**Comment by wangzhishi** [comment]
this seems to be a duplicated issue as #699
