### ISSUE TITLE
Hyperparameter Tuning

### ISSUE THREAD

**Issue by dromare** [uber/orbit#658]
**Is your feature request related to a problem? Please describe.**
Say we have this search space:
```
param_grid = {
 'level_sm_input': [0.3, 0.5, 0.8],
 'seasonality_sm_input': [0.3],
 'slope_sm_input': [0.3],
 'regression_penalty': ['fixed_ridge', 'auto_ridge'],
 'auto_ridge_scale': [0.1, 0.9],
 'damped_factor': [0.3],
 'global_trend_option': ['linear']
}
```
```
best_params, tuned_df = grid_search_orbit(param_grid,
                                        model=dlt,
                                        df=data,
                                        min_train_len=min_train_len,
                                        incremental_len=incremental_len,
                                        forecast_len=forecast_len,
                                        metrics=None, criteria=None, verbose=True)
```

The CV grid consists of 3 x 2 x 3 = 12 combinations.
However, one would expect Orbit to run through only 9 combinations:

- 3 `'level_sm_input'` values x 2 `'auto_ridge_scale'` values when `'regression_penalty' =' auto_ridge'`

- 3 `'level_sm_input'` values when `'regression_penalty' = 'fixed_ridge'` (`'auto_ridge_scale'` is not used)

`tuned_df.sort_values(['metrics'])` proves there are 3 redundant model runs (entries 6, 8 and 10 are duplicates of entries 0, 2 and 4):

![image](https://user-images.githubusercontent.com/90710133/147492802-db97d02f-a6d1-499e-b191-a32d6201b4e1.png)

`best_params` has length 2:
```
[{'auto_ridge_scale': 0.1,
  'damped_factor': 0.3,
  'global_trend_option': 'linear',
  'level_sm_input': 0.3,
  'regression_penalty': 'fixed_ridge',
  'seasonality_sm_input': 0.3,
  'slope_sm_input': 0.3},
 {'auto_ridge_scale': 0.9,
  'damped_factor': 0.3,
  'global_trend_option': 'linear',
  'level_sm_input': 0.3,
  'regression_penalty': 'fixed_ridge',
  'seasonality_sm_input': 0.3,
  'slope_sm_input': 0.3}]
```
hence one has to take `best_params[0]`
**Describe the solution you'd like**
Remove redundant model runs thus speeding up hyperparameter tuning.

**Describe alternatives you've considered**
Filter out redundant runs inside the grid search function; `'auto_ridge_scale'` and `'lasso_scale' `are only used when `'regression_penalty' `is '`auto_ridge' `and `'lasso'`, respectively.

**Additional context**

**Comment by wangzhishi** [comment]
IMO, this is something you can avoid by preparing a more reasonable grid of parameters.

**Comment by edwinnglabs** [comment]
@dromare In general, if there are interactions across hyper-parameters where one will not be valid when certain value specified in other hyper-parameters, i would recommend you to decompose them into two separate grid search. It would be beyond our scope right now to make that dynamics happens within the simple grid search function.  Meanwhile, we are preparing a statistics WBIC where you can compare models across different structure in a Bayesian way.

**Comment by skyesheng** [comment]
One follow up question.
Say I get the best_params from grid search method. How do I use that set of hyperparameters and fit a model? Or is the model with the best set of hyperparameters retrievable from grid_search_orbit method?

**Comment by edwinnglabs** [comment]
> 

you can pass the parameters back to fit a final model something like
```
final_mod = DLT(..., **best_params)
```

**Comment by edwinnglabs** [comment]
> you can pass the parameters back to fit a final model something like
> 
> ```
> final_mod = DLT(..., **best_params)
> ```



> One follow up question. Say I get the best_params from grid search method. How do I use that set of hyperparameters and fit a model? Or is the model with the best set of hyperparameters retrievable from grid_search_orbit method?

you can pass the parameters back to fit a final model something like

final_mod = DLT(..., **best_params)
