### ISSUE TITLE
Error when we use 1 regressor in KTR

### ISSUE THREAD

**Issue by denix56** [uber/orbit#664]
Matrix multiplication error when we use only 1 regressor in KTR.
The bug is caused by invalid expand_dims parameter in ktr.

Instead of:
```
if len(self._regressor_col) == 1:
    coef_knots = np.expand_dims(coef_knots, -1)
```
it should be 
```
if len(self._regressor_col) == 1:
    coef_knots = np.expand_dims(coef_knots, -2)
```

**Comment by edwinnglabs** [comment]
May I know which branch you are running? `master` or `dev`?

**Comment by denix56** [comment]
@edwinnglabs dev branch

**Comment by wangzhishi** [comment]
@denix56 
actually, in the code base of dev branch, it doesn't look like what you pointed out above,
it is 
```
if len(self._regressor_col) == 1:
    coef_knots = np.expand_dims(coef_knots, 1)
```
https://github.com/uber/orbit/blob/dev/orbit/template/ktr.py#L1026

It passed the single regressor unit test from our side. Not sure why it doesn't work on your end. do you have a minimal reproducible example?
