### ISSUE TITLE
Typo Kernel-based Time-varying Regression - Part I Tutorial

### ISSUE THREAD

**Issue by juanitorduz** [uber/orbit#669]
Hey! I am going through the very nice tutorials on Kernel-based Time-varying Regression. I have a question about the notation. In Part I where you explain and introduce the latent variables (Model Structure section ) you say:

*... To reduce the total number of parameters in the model (potentially P x t)* Should not it be P x T ?

Similarly, a couple lines below you say:

*... where - coefficient matrix B has size t x P* Should not it be T x P ?

If this is the case I can create a PR...but I just want to understand if my understanding is correct. Thanks :)

**Comment by edwinnglabs** [comment]
Thank you for pointing this out @juanitorduz please feel free to make the change you proposed.  Somehow I feel there is some cosmetic issue as well where some funny things are interacting with the latex rendering. FYI @wangzhishi
