### ISSUE TITLE
Add a `conda` install option for `orbit-ml`

### ISSUE THREAD

**Issue by sugatoray** [uber/orbit#674]
A conda installation option could be helpful. I have started working on adding `orbit-ml` to conda-forge channel (PR: https://github.com/conda-forge/staged-recipes/pull/17563). Once the PR gets merged you will be able to install the library with:

```sh
conda install -c conda-forge orbit-ml
```

:bulb: I will push a PR to update the readme/docs once it is available on conda-forge.

**Comment by edwinnglabs** [comment]
@sugatoray do you have any idea how to implement this?

**Comment by sugatoray** [comment]
@edwinnglabs Please see the PR I mentioned above.

- https://github.com/conda-forge/staged-recipes/pull/17563

**Comment by sugatoray** [comment]
:rocket: Now it's available on conda-forge.

![image](https://user-images.githubusercontent.com/10201242/150082077-53f717db-49aa-449b-9477-4427cf6be83b.png)

cc: @edwinnglabs
