### ISSUE TITLE
import ETS undefined symbol: _ZSt28__throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by hiwaveSupport** [uber/orbit#675]
Getting this issue when executing >>> from orbit.models import ETS
Used pip install orbit-ml
Orbit installed successfully with some hiccup related to pystan installation, which reverted back to setup.py way to install.

`
Requirement already satisfied: pystan in /home/vibhu/miniconda3/envs/orbit/lib/python3.9/site-packages (2.19.1.1)
Requirement already satisfied: Cython!=0.25.1,>=0.22 in /home/vibhu/miniconda3/envs/orbit/lib/python3.9/site-packages (from pystan) (0.29.26)
Requirement already satisfied: numpy>=1.7 in /home/vibhu/miniconda3/envs/orbit/lib/python3.9/site-packages (from pystan) (1.22.1)
`
O/S
`
Linux pop-os 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux
`

Error:
`ImportError: /home/vibhu/miniconda3/envs/orbit/lib/python3.9/site-packages/pystan/_api.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv`

Please advise what is best way to resolve this?

**Comment by edwinnglabs** [comment]
@hiwaveSupport is this still valid?
