### ISSUE TITLE
Confirm if the Slack link is correct

### ISSUE THREAD

**Issue by paullo0106** [uber/orbit#676]
**Describe the bug**
When I click on the [Join Slack](https://app.slack.com/client/T01BMFW7VG9/C01AU51F11V) link, am I supposed to be redirected to Orbit's workspace directly? I'm seeing an input text area for the workspace 🤔

**To Reproduce**
Click [Join Slack](https://app.slack.com/client/T01BMFW7VG9/C01AU51F11V) link on Readme

**Expected behavior**
Getting redirected to Orbit's workspace directly without having to enter workspace

**Screenshots**
![Screen Shot 2022-01-17 PM](https://user-images.githubusercontent.com/4966393/149851325-3047ab99-b645-4a01-8d39-dcef9e982451.png)

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by edwinnglabs** [comment]
@paullo0106 how about this [one](https://orbit-support.slack.com/ssb/redirect)?

**Comment by edwinnglabs** [comment]
Looking into it, I find the setting is accidentally set to `expire in 30 days`.  I just fix the link now. Thank you for catching this.
