### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.7/dist-packages/orbit/plot_style.mplstyle'

### ISSUE THREAD

**Issue by JeremyWhittaker** [uber/orbit#690]
**Describe the bug**
I'm trying to use the example in the quickstart guide. When I try to plot I get the following error, No such file or directory: '/usr/local/lib/python3.7/dist-packages/orbit/plot_style.mplstyle' 

**To Reproduce**
quickstart guide

**Expected behavior**
Plotted data 
![image](https://user-images.githubusercontent.com/13750325/150400524-46cff3c0-dff5-4085-bd68-e2461ca5bc51.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/13750325/150400571-9c9c5e8f-8bab-4fe7-b3ca-976611376006.png)

**Environment (please complete the following information):**
Colab

**Comment by JeremyWhittaker** [comment]
I was able to clone this file from git and it solved the issue. I'm just not sure why it didn't copy over originally.

**Comment by edwinnglabs** [comment]
Thanks for providing the feedback.  I suspect the latest `dev` version might have solved this problem where we introduce `try-exception` block to allow plotting without the style file.  I would expect a better solution tho is to ensure the file is there after installation @wangzhishi

**Comment by wangzhishi** [comment]
> Hi, I got the same issue on orbit 1.1.0. Is there a fix available?

Hi @robertosannazzaro , on what OS/env were you calling orbit? also on Colab?

**Comment by dsanyal** [comment]
I'm also facing the same issue on Colab and Jupyterhub instance. I'm on version 1.1.0.
I bypassed it by using `use_orbit_style=False`, but then the resulting plot is ugly.

**Comment by edwinnglabs** [comment]
I can also replicate the error while using Anaconda in windows

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Anaconda3\envs\noom\lib\site-packages\matplotlib\style\core.py in use(style)
    126             try:
--> 127                 rc = rc_params_from_file(style, use_default_template=False)
    128                 _apply_style(rc)

~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
    851     """
--> 852     config_from_file = _rc_params_in_file(fname, fail_on_error=fail_on_error)
    853 

~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in _rc_params_in_file(fname, transform, fail_on_error)
    777     rc_temp = {}
--> 778     with _open_file_or_url(fname) as fd:
    779         try:

~\Anaconda3\envs\noom\lib\contextlib.py in __enter__(self)
    111         try:
--> 112             return next(self.gen)
    113         except StopIteration:

~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in _open_file_or_url(fname)
    754             encoding = "utf-8"
--> 755         with open(fname, encoding=encoding) as f:
    756             yield f
```

**Comment by edwinnglabs** [comment]
> I can also replicate the error while using Anaconda in windows
> 
> ```
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> ~\Anaconda3\envs\noom\lib\site-packages\matplotlib\style\core.py in use(style)
>     126             try:
> --> 127                 rc = rc_params_from_file(style, use_default_template=False)
>     128                 _apply_style(rc)
> 
> ~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
>     851     """
> --> 852     config_from_file = _rc_params_in_file(fname, fail_on_error=fail_on_error)
>     853 
> 
> ~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in _rc_params_in_file(fname, transform, fail_on_error)
>     777     rc_temp = {}
> --> 778     with _open_file_or_url(fname) as fd:
>     779         try:
> 
> ~\Anaconda3\envs\noom\lib\contextlib.py in __enter__(self)
>     111         try:
> --> 112             return next(self.gen)
>     113         except StopIteration:
> 
> ~\Anaconda3\envs\noom\lib\site-packages\matplotlib\__init__.py in _open_file_or_url(fname)
>     754             encoding = "utf-8"
> --> 755         with open(fname, encoding=encoding) as f:
>     756             yield f
> ```

@wangzhishi
