### ISSUE TITLE
Dynamic path in the compile_stan_model.

### ISSUE THREAD

**Issue by icarofua** [uber/orbit#709]
**Is your feature request related to a problem? 
In our platform, we have the following issue:

PermissionError: [Errno 13] Permission denied: '/mnt/datadisk1/dataiku/dataiku/code-envs/python/orbit-ml-py/lib/python3.6/site-packages/orbit/stan_compiled'

**Describe the solution you'd like**
In the compile_stan_model function can you add a new parameter that will be the path for the compiled_model to save.

**Comment by wangzhishi** [comment]
we have a branch, `dev-config-stan-path`, to have this feature. For example, you can use

```
from orbit.utils import set_compiled_stan_path
set_compiled_stan_path("/Users/xxx/xxx")
```
to customize the path.

Right now the PR is subject to review. Meanwhile, you may take a try by using the branch? Let us know if it works for your purpose.

**Comment by icarofua** [comment]
It works amazing.
