### ISSUE TITLE
conda install 

### ISSUE THREAD

**Issue by wangzhishi** [uber/orbit#741]
will `conda install -c conda-forge orbit-ml` have the latest version installed?

**Comment by ppstacy** [comment]
hey @sugatoray thanks a lot for your continue contributions of maintain Orbit version for conda. I saw you updated the recent version on Mar 8th here (https://github.com/conda-forge/orbit-ml-feedstock/commits/main/recipe/meta.yaml). Just wondering do you have any automated procedures to update after a new release or it's manually? Thanks a lot!!

**Comment by ppstacy** [comment]
Thanks a lot @sugatoray!! Wondering if you can share the conda-forge bot with the Orbit team as well? So we could also monitor and help when it fail. Thanks again!

**Comment by sugatoray** [comment]
@ppstacy The bot is already applied to the feedstock. There's nothing more to do there. These boys are developed and maintained by the conda-forge community members. What will be more helpful, is if you can name a few (1-2) orbit-ml core-contributors, who could become co-maintainers of the feedstock alongside me. 

So far, I have authored close to around 45+ conda-forge packages. I have worked on other few such collaborations to maintain conda-forge packages with maintainers from the upstream package repositories. And would be glad to help the new co-maintainers learn the ropes of conda-forge feedstock maintenance.

Please let me know if you can suggest a few names.

**Comment by ppstacy** [comment]
@sugatoray Thanks for the valuable information here. I didn't know the bot been applied already. Does this automatically apply to all  projects or you added for Orbit?

I think @wangzhishi @edwinnglabs are the main maintainers for Orbit. Please see @sugatoray's comment above and submit a PR once we have a new release.

**Comment by sugatoray** [comment]
There are two boys. The one that looks for newer versions and sends a PR to update the feedstock recipe, is typically setup at the moment the feedstock is created. So, that's quite standard for all feedstocks. 

There is another bot, that automatically merges a successful PR (given all CI runs succeed). This one, I manually added to the feedstock later. 

Most often, you don't have to touch the recipe. However, when you add any dependencies, then you would have to update the recipe in the feedstock as well. And if you add any python library which is not already added to conda-forge, then you will need to add that recipe on conda-forge as a fresh recipe. 

Please take a look at the open PRs on https://github.com/conda-forge/seqlike-feedstock and you will see a similar scenario: there is a PR from me that points to another open PR on https://github.com/conda-forge/staged-recipes.

**Comment by ppstacy** [comment]
@sugatoray thanks a lot and this is super clear!! Thanks again for helping maintain Orbit!

**Comment by wangzhishi** [comment]
thanks for all the info, @sugatoray. very helpful.

**Comment by sugatoray** [comment]
Happy to help @wangzhishi
