### ISSUE TITLE
DLTMAP has no way of setting cores=1

### ISSUE THREAD

**Issue by martinmenchon** [uber/orbit#757]
Hi all,
I was trying to use DLTMAP with cores=1 but there is no way of setting that. The "cores" value is not used inside DLTMAP.

Hope you can help me,
Regards!

**Comment by wangzhishi** [comment]
Hi @martinmenchon, orbit uses pystan under the hood for the MAP optimization. actually, there is no option to set number of computing cores for MAP in Stan. You will get more context by checking out pystan's optimizing API: https://pystan2.readthedocs.io/en/latest/api.html

**Comment by martinmenchon** [comment]
But it says “n_jobs” I think it was recently added. I will try it and make a PR
![448BE845-5EA1-446A-9FD5-4FBCACD750A5](https://user-images.githubusercontent.com/5431771/176567333-42c087be-9ccf-49cc-822d-6673c49ce400.jpeg)

**Comment by wangzhishi** [comment]
the one you are looking at is for MCMC inference in stan, not MAP. You original question was asking about MAP estimator, so you should look at this one
<img width="707" alt="image" src="https://user-images.githubusercontent.com/7907663/176577590-a55bcd16-b0f4-4ddb-a70e-fdab581a0ff5.png">
