### ISSUE TITLE
test_plot.py::test_plot_predicted_data hangs on M1 macOS

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/orbit#766]
**Describe the bug**
`test_plot.py::test_plot_predicted_data` test hangs on M1 macOS.

**To Reproduce**
Steps to reproduce the behavior: Run `pytest tests/orbit/diagnostics/test_plot.py::test_plot_predicted_data` on M1 macOS

**Expected behavior**
Test 

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu] M1 macOS
 - Python Version: [e.g. 3.6, 3.7] 3.8
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]
```
Cython==0.29.30
matplotlib==3.5.2
numpy==1.23.0
opt-einsum==3.3.0
pandas==1.4.3
pyro-api==0.1.2
pyro-ppl==1.8.1
pystan==2.19.1.1
pytest==7.1.2
pytest-cov==3.0.0
scipy==1.8.1
seaborn==0.11.2
statsmodels==0.13.2
torch==1.11.0
```

**Additional context**
N/A

**Comment by edwinnglabs** [comment]
Try the steps below.  It works for me.
```
brew install hdf5 netcdf
git clone https://github.com/Unidata/netcdf4-python.git
HDF5_DIR=$(brew --prefix hdf5) pip install ./netcdf4-python
```

**Comment by jeongyoonlee** [comment]
Couldn't reproduce the issue anymore.

**Comment by f0rodo** [comment]
hi @jeongyoonlee  how did you install pystan 2.9.11 on your m1? I haven't been able to.
