### ISSUE TITLE
Occasional crash in distributed training and prediction of DLT models due to pystan

### ISSUE THREAD

**Issue by ggerogiokas** [uber/orbit#787]
When I run roughly 10,000 different time series,  I get runs crashing for various reasons.
They typically only relate to two errors:

**pickle data was truncated** 
or 
**Ran out of input.**

Both seem to relate to stan compilation issues.

Any tips on how to avoid these issues.

I am running on ubuntu, with python 3.8 so don't think it's an OS issue.

**Comment by edwinnglabs** [comment]
Can you provide some data / object snapshot when the issue happen? @ggerogiokas
