### ISSUE TITLE
Error while running ets.fit : distutils.errors.DistutilsExecError: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1

### ISSUE THREAD

**Issue by diagnolytics** [uber/orbit#789]
**Describe the bug**
I am having issues running Pystan package. I have installed GCC compiler and also set path to C:\\MinGW\\bin\\gcc.exe. I have also created disutils.cfg file as per the instructions on different forums. I am still unable to run Orbit ML code. 

**Screenshots**
<
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f7eb4ed4486a30ffc26b04f2ada67b48 NOW.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 173, in _compile
    extra_postargs)
  File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/ProgramData/Anaconda3/envs/Forecasting_Algorithms/orbit_ml.py", line 35, in <module>
    ets.fit(df=train_df)
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\forecaster\full_bayes.py", line 29, in fit
    super().fit(df, sampling_temperature=sampling_temperature)
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\forecaster\forecaster.py", line 169, in fit
    **kwargs,
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\estimators\stan_estimator.py", line 118, in fit
    compiled_stan_file = get_compiled_stan_model(model_name)
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\utils\stan.py", line 62, in get_compiled_stan_model
    compiled_model = compile_stan_model(stan_model_name)
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\utils\stan.py", line 49, in compile_stan_model
    sm = StanModel(model_code=model_code)
  File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\pystan\model.py", line 378, in __init__
    build_extension.run()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 175, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\MinGW\\bin\\gcc.exe' failed with exit status 1
> 

**Environment (please complete the following information):**
 - OS: Windows 
 - Python Version: 3.6.5:: Anaconda, Inc.
 - Versions of Major Dependencies GCC: gcc (MinGW.org GCC Build-2) 9.2.0

Let me know how I can resolve this issue. I appreciate the help from the community.

**Comment by skyesheng** [comment]
Encounter the same error using Mac OS

**Comment by edwinnglabs** [comment]
> **Describe the bug** I am having issues running Pystan package. I have installed GCC compiler and also set path to C:\MinGW\bin\gcc.exe. I have also created disutils.cfg file as per the instructions on different forums. I am still unable to run Orbit ML code.
> 
> **Screenshots** < INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_f7eb4ed4486a30ffc26b04f2ada67b48 NOW. Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 173, in _compile extra_postargs) File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 909, in spawn spawn(cmd, dry_run=self.dry_run) File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 38, in spawn _spawn_nt(cmd, search_path, dry_run=dry_run) File "C:\ProgramData\Anaconda3\lib\distutils\spawn.py", line 81, in _spawn_nt "command %r failed with exit status %d" % (cmd, rc)) distutils.errors.DistutilsExecError: command 'C:\MinGW\bin\gcc.exe' failed with exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:/ProgramData/Anaconda3/envs/Forecasting_Algorithms/orbit_ml.py", line 35, in ets.fit(df=train_df) File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\forecaster\full_bayes.py", line 29, in fit super().fit(df, sampling_temperature=sampling_temperature) File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\forecaster\forecaster.py", line 169, in fit **kwargs, File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\estimators\stan_estimator.py", line 118, in fit compiled_stan_file = get_compiled_stan_model(model_name) File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\utils\stan.py", line 62, in get_compiled_stan_model compiled_model = compile_stan_model(stan_model_name) File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\orbit\utils\stan.py", line 49, in compile_stan_model sm = StanModel(model_code=model_code) File "C:\ProgramData\Anaconda3\envs\Temp\Forecasting_Algorithms\lib\site-packages\pystan\model.py", line 378, in **init** build_extension.run() File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run self.build_extensions() File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 448, in build_extensions self._build_extensions_serial() File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial self.build_extension(ext) File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension depends=ext.depends) File "C:\ProgramData\Anaconda3\lib\distutils\ccompiler.py", line 574, in compile self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts) File "C:\ProgramData\Anaconda3\lib\distutils\cygwinccompiler.py", line 175, in _compile raise CompileError(msg) distutils.errors.CompileError: command 'C:\MinGW\bin\gcc.exe' failed with exit status 1
> 
> > 
> 
> **Environment (please complete the following information):**
> 
> * OS: Windows
> * Python Version: 3.6.5:: Anaconda, Inc.
> * Versions of Major Dependencies GCC: gcc (MinGW.org GCC Build-2) 9.2.0
> 
> Let me know how I can resolve this issue. I appreciate the help from the community.

could you try a higher version of python such as 3.7 and 3.8?

**Comment by edwinnglabs** [comment]
> Encounter the same error using Mac OS

@skyesheng you may want to try the `dev-114-cmdstanpy` branch and see the if the problem still exists.

**Comment by skyesheng** [comment]
Thank you for your reply.

Here is the error message when I clone dev-114-cmdstan.

ERROR: Failed building wheel for orbit-ml
Failed to build orbit-ml
ERROR: Could not build wheels for orbit-ml, which is required to install pyproject.toml-based projects

Please advise further. Thank you!

Skye Sheng
NA Data Science | Home Care
[Icon  Description automatically generated]

From: Edwin Ng ***@***.***>
Date: Wednesday, January 11, 2023 at 10:36 PM
To: uber/orbit ***@***.***>
Cc: Sheng, Skye ***@***.***>, Mention ***@***.***>
Subject: Re: [uber/orbit] Error while running ets.fit : distutils.errors.DistutilsExecError: command 'C:\MinGW\bin\gcc.exe' failed with exit status 1 (Issue #789)
[EXTERNAL]


Encounter the same error using Mac OS

@skyesheng<https://urldefense.com/v3/__https:/github.com/skyesheng__;!!NgSi4SaN6ydtRVQ-!1zoeMhGfOUDEdjw84TL8qtU1-87gOrTejPNNwqpQylL5Mv-F031OjspqSrLBAbPLQhj7hzfZhT_wkC9Zh9UAzw$> you may want to try the dev-114-cmdstanpy branch and see the if the problem still exists.

**Comment by edwinnglabs** [comment]
could you share more information how you install the package? @skyesheng

**Comment by skyesheng** [comment]
> could you share more information how you install the package? @skyesheng

Here is the environment I am working in
OS: Mac OS Monterey - version 12.0.1
Python: 3.8

I tried the followings as listed in README
1. git clone https://github.com/uber/orbit.git
    cd orbit
    pip install -r requirements.txt
    pip install .

2. pip install git+https://github.com/uber/orbit.git@dev

All render the same error

INFO:numexpr.utils:Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
WARNING:matplotlib:
Bad key text.latex.preview in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 123 ('text.latex.preview : False')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
WARNING:matplotlib:
Bad key mathtext.fallback_to_cm in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 155 ('mathtext.fallback_to_cm : True  # When True, use symbols from the Computer Modern')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
WARNING:matplotlib:
Bad key savefig.jpeg_quality in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 418 ('savefig.jpeg_quality: 95       # when a jpeg is saved, the default quality parameter.')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
WARNING:matplotlib:
Bad key keymap.all_axes in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 466 ('keymap.all_axes : a                 # enable all axes')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
WARNING:matplotlib:
Bad key animation.avconv_path in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 477 ('animation.avconv_path: avconv     # Path to avconv binary. Without full path')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
WARNING:matplotlib:
Bad key animation.avconv_args in file /opt/anaconda3/lib/python3.8/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle, line 479 ('animation.avconv_args:            # Additional arguments to pass to avconv')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.6.2/matplotlibrc.template
or from the matplotlib source distribution
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_fe66aa2462adfc8a93558d083eea540a NOW.
---------------------------------------------------------------------------
DistutilsExecError                        Traceback (most recent call last)
/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    185         try:
--> 186             self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    187         except DistutilsExecError as msg:

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py in spawn(self, cmd, **kwargs)
   1006     def spawn(self, cmd, **kwargs):
-> 1007         spawn(cmd, dry_run=self.dry_run, **kwargs)
   1008 

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/spawn.py in spawn(cmd, search_path, verbose, dry_run, env)
     69             cmd = cmd[0]
---> 70         raise DistutilsExecError(
     71             "command {!r} failed with exit code {}".format(cmd, exitcode)

DistutilsExecError: command '/usr/local/bin/gcc-10' failed with exit code 1

During handling of the above exception, another exception occurred:

CompileError                              Traceback (most recent call last)
<ipython-input-3-5589e5342b92> in <module>
     15   seasonality=52,
     16 )
---> 17 dlt.fit(df=train_df)
     18 
     19 # outcomes data frame

/opt/anaconda3/lib/python3.8/site-packages/orbit/forecaster/full_bayes.py in fit(self, df, point_method, keep_samples, sampling_temperature, **kwargs)
     34         **kwargs,
     35     ):
---> 36         super().fit(df, sampling_temperature=sampling_temperature, **kwargs)
     37         self._point_method = point_method
     38 

/opt/anaconda3/lib/python3.8/site-packages/orbit/forecaster/forecaster.py in fit(self, df, **kwargs)
    161         # estimator type and model_name provided
    162 
--> 163         _posterior_samples, training_metrics = estimator.fit(
    164             model_name=model_name,
    165             model_param_names=model_param_names,

/opt/anaconda3/lib/python3.8/site-packages/orbit/estimators/stan_estimator.py in fit(self, model_name, model_param_names, sampling_temperature, data_input, fitter, init_values)
    116         init_values=None,
    117     ):
--> 118         compiled_stan_file = get_compiled_stan_model(model_name)
    119 
    120         #   passing callable from the model as seen in `initfun1()`

/opt/anaconda3/lib/python3.8/site-packages/orbit/utils/stan.py in get_compiled_stan_model(stan_model_name)
     59     """
     60 
---> 61     compiled_model = compile_stan_model(stan_model_name)
     62 
     63     with open(compiled_model, "rb") as f:

/opt/anaconda3/lib/python3.8/site-packages/orbit/utils/stan.py in compile_stan_model(stan_model_name)
     46             model_code = f.read()
     47 
---> 48         sm = StanModel(model_code=model_code)
     49 
     50         with open(compiled_model, "wb") as f:

/opt/anaconda3/lib/python3.8/site-packages/pystan/model.py in __init__(self, file, charset, model_name, model_code, stanc_ret, include_paths, boost_lib, eigen_lib, verbose, obfuscate_model_name, extra_compile_args, allow_undefined, include_dirs, includes)
    376 
    377         try:
--> 378             build_extension.run()
    379         finally:
    380             if redirect_stderr:

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py in run(self)
    344 
    345         # Now actually compile and link everything.
--> 346         self.build_extensions()
    347 
    348     def check_extensions_list(self, extensions):  # noqa: C901

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py in build_extensions(self)
    466             self._build_extensions_parallel()
    467         else:
--> 468             self._build_extensions_serial()
    469 
    470     def _build_extensions_parallel(self):

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py in _build_extensions_serial(self)
    492         for ext in self.extensions:
    493             with self._filter_build_errors(ext):
--> 494                 self.build_extension(ext)
    495 
    496     @contextlib.contextmanager

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py in build_extension(self, ext)
    547             macros.append((undef,))
    548 
--> 549         objects = self.compiler.compile(
    550             sources,
    551             output_dir=self.build_temp,

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py in compile(self, sources, output_dir, macros, include_dirs, debug, extra_preargs, extra_postargs, depends)
    597             except KeyError:
    598                 continue
--> 599             self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    600 
    601         # Return *all* object filenames, not just the ones we just built.

/opt/anaconda3/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py in _compile(self, obj, src, ext, cc_args, extra_postargs, pp_opts)
    186             self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    187         except DistutilsExecError as msg:
--> 188             raise CompileError(msg)
    189 
    190     def create_static_lib(

CompileError: command '/usr/local/bin/gcc-10' failed with exit code 1

**Comment by edwinnglabs** [comment]
@skyesheng are you installing v1.1.4.2? and are you using pip or conda?
