### ISSUE TITLE
cmdstanpy instead of pystan

### ISSUE THREAD

**Issue by juanitorduz** [uber/orbit#793]
Hi! Is there any plan to move from `pystan` to `cmdstanpy`? The installation is sometimes hard because of, for example https://discourse.mc-stan.org/t/error-installing-pystan-in-python-3-10-with-gcc-9-2-0/27895/7

**Comment by edwinnglabs** [comment]
Totally Agree.  Exploring `cmdstanpy` and `numpyro` is one of the core tasks in our roadmap.

**Comment by juanitorduz** [comment]
Amazing! 🚀

**Comment by edwinnglabs** [comment]
Currently, `cmdstanpy` API is under testing in this [branch](https://github.com/uber/orbit/tree/dev-114-cmdstan).  Core tasks include
- [ ] DLT
- [ ] LGT
- [ ] ETS
- [ ] KTRLite
- [ ] diagnostics (chains properties)

**Comment by juanitorduz** [comment]
Amazing 🙌 !
