### ISSUE TITLE
Failed building wheel for orbit-ml

### ISSUE THREAD

**Issue by udheep123** [uber/orbit#811]
**Describe the bug**
failed building wheel for orbit-ml
**To Reproduce**
pip install orbit-ml on ubuntu instance
**Expected behavior**
Run and successfully install the orbit-ml package
**Screenshots**
<img width="960" alt="Untitled" src="https://github.com/uber/orbit/assets/84394591/8e590157-682f-493c-b84a-bdbf812a8fa1">

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `sciki
t-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by ani-rag** [comment]
I am getting the same error. I tried using a fresh conda environment with Python 3.9 in Mac M2

**Comment by ar-asur** [comment]
I am getting the same error. I tried using a fresh conda environment with Python 3.9 in Mac M2

**Comment by kaizenlabs** [comment]
Same, can't even install it to try out.

**Comment by edwinnglabs** [comment]
> Same, can't even install it to try out.

@ar-asur @kaizenlabs conda recipe is updated and should be using the latest version. Can you try it out?

**Comment by ar-asur** [comment]
Hi @edwinnglabs 

I tried again and was able to install the package successfully with `conda install -c conda-forge orbit-ml`. But when i tried to execute the code from `ktr.ipynb`, I got error `ValueError: Failed to compile Stan model` when I run the `fit` function.

**Comment by georgehaws** [comment]
I had the "Failed building wheel" problem too.  Now I don't and everything works.

I only had like 8gb of ram.

**I upgraded to 32gb of ram and the problem went away faster than an embarrassed Homer Simpson fading into the shrubberies...**
