### ISSUE TITLE
Support more flexible prediction range or improve documentation about prediction range.

### ISSUE THREAD

**Issue by Eve-Chen** [uber/orbit#815]
**Is your feature request related to a problem? Please describe.**
If forecast range starts after train end date, the forecaster interface assumes the forecast range starts right after train end date ([this line](https://github.com/uber/orbit/blob/e247c1c2135b1b8f7aea4e5357e8570956bc7edb/orbit/forecaster/forecaster.py#L345)). Can we remove that hard assumption and allow a gap between train end date and forecast start date? i.e. prediction range = [train end date + gap, train end date + gap + n_forecast_steps]. 

**Describe the solution you'd like**
Support generic scenario where prediction range = [train start date + x, train start date + x + n_forecast_steps].  This would cover the current supported use cases, and the case where there is a gap between prediction range and train range. 

**Describe alternatives you've considered**
Explicitly state the assumption in API documentation, and add warning about the gap (if exists) and the current handling about the gap. 

**Additional context**

**Comment by edwinnglabs** [comment]
Wouldn't it be easier for user to trim the forecast range since the model is generate which requires forecast at T to generate forecast at T+1?
