### ISSUE TITLE
cannot import name 'DLTFull' from 'orbit.models.dlt'

### ISSUE THREAD

**Issue by KathyGCY** [uber/orbit#818]
**Describe the bug**
`ImportError: cannot import name 'DLTFull' from 'orbit.models.dlt' (/usr/local/share/sciencebox/venv/lib/python3.9/site-packages/orbit/models/dlt.py)
`

**To Reproduce**
`from orbit.models.dlt import DLTFull`

**Expected behavior**
Expect to have something like this demo in [techdoc](https://uber.github.io/orbit/tutorials/regression.html)

**Screenshots**
<img width="1163" alt="Screenshot 2023-08-02 at 1 43 23 PM" src="https://github.com/uber/orbit/assets/14912791/b498437d-da88-4bbd-9bfe-daa84144bb19">

**Environment (please complete the following information):**
 - OS: [jovyan@jupyter-513f37af833e5885a9a269c9c8888925-kathyg:~$]
 - Python Version: [e.g. 3.9.12]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by markdoughten** [comment]
Seems like the documentation is outdated, the new name is DLT. Link: https://github.com/uber/orbit/blob/dev/orbit/models/dlt.py

**Comment by edwinnglabs** [comment]
please use the read the docs link displayed in the main github page instead: 
[](https://orbit-ml.readthedocs.io/en/stable/)
