### ISSUE TITLE
Forecast is Not connected to latest actuals

### ISSUE THREAD

**Issue by KathyGCY** [uber/orbit#819]
**Describe the bug**
Forecast not connected to latest actuals. Time series has seasonality 7 and global_trend_option flat and forcing a positive regressor sign. The regressor has no structural break whatsoever, but somehow the forecast is not connected to the last train date value

**To Reproduce**
Cannot due to data confidentiality

**Expected behavior**
Expect forecast to start somewhat close to last train date value. 

**Screenshots**
Cannot due to data confidentiality

**Environment (please complete the following information):**
 - OS: [macOS]
 - Python Version: [3.9.12]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**

**Comment by edwinnglabs** [comment]
@KathyGCY are you running DLT or KTR? can you elaborate a little more what you mean by "the forecast is not connected to the last train date value"?
